### ISSUE TITLE
Error with 32bit record size

### ISSUE THREAD

**Issue by coderholic** [PaddeK/node-maxmind-db#11]
If you try and read an mmdb with a 32bit record size you get the following error:

```
TypeError: Cannot call method 'readUInt32BE' of undefined
  at [object Object].readNode ( node_modules/maxmind-db-reader/lib/Reader.js:130:26)
  at [object Object].findAddressInTree ( node_modules/maxmind-db-reader/lib/Reader.js:93:23)
  at [object Object].getSync ( node_modules/maxmind-db-reader/lib/Reader.js:59:24)
  at [object Object].getGeoDataSync ( node_modules/maxmind-db-reader/index.js:34:24)
```

Looking at the code at https://github.com/PaddeK/node-maxmind-db/blob/master/lib/Reader.js#L130 it seems that bytes it never set for this code path

**Comment by EaterOfCode** [comment]
Im sorry for reacting late, do you have an mmdb with 32bit record size for me to test? or can you confirm that changing `bytes` to `buffer` on line 130 resolves the issue? :)

**Comment by oschwald** [comment]
MaxMind provides [a 32-bit test database](https://github.com/maxmind/MaxMind-DB/blob/master/test-data/MaxMind-DB-test-mixed-32.mmdb). It should have 1.1.1.1-1.1.1.32 and :1:ffff:ffff-::2:0000:0059 in it.

**Comment by EaterOfCode** [comment]
Oh sweet, thanks :) will look into it now.

**Comment by EaterOfCode** [comment]
Is fixed now and published on npm :)
