### ISSUE TITLE
node-maxmind-db hangs indefinitely on feeding corrupt db file

### ISSUE THREAD

**Issue by rajeshsegu** [PaddeK/node-maxmind-db#15]
Have a zero bytes db file
```
> touch GeoIP2-City-Zero.mmdb
```
node.js
```
var MaxMindDBReader = require('maxmind-db-reader');
MaxMindDBReader.openSync(<dbPath-to-GeoIP2-City-Zero.mmdb>)
```

the module gets stuck and never errors out. Can we fix this please ??

**Comment by rajeshsegu** [comment]
@PaddeK @EaterOfCode looks like this case was hanging on infinite while loop and also adding unit tests to handle it. let me know if you want me to make further changes.

Let me know if you are planning to work on node-geoip2 library, I would be happy to contribute.

**Comment by EaterOfCode** [comment]
Thanks for the help, feel free to make more pull requests.
