### ISSUE TITLE
Error - Unknown or unexpected type: undefined at offset:141337693

### ISSUE THREAD

**Issue by ladas-larry** [PaddeK/node-maxmind-db#23]
With the latest data I'm getting "MaxmindDBReader: Unknown or unexpected type: undefined at offset:141337693". That happens regardless of ip address location.

**Comment by Dharmoslap** [comment]
<img width="966" alt="screen shot 2015-12-03 at 09 56 30" src="https://cloud.githubusercontent.com/assets/3543614/11555987/496b4306-99a4-11e5-9f0e-91ff3596e284.png">

**Comment by ladas-larry** [comment]
<img width="962" alt="screen shot 2015-12-03 at 09 57 48" src="https://cloud.githubusercontent.com/assets/3543614/11556002/5c75e398-99a4-11e5-85d7-c6c3d535993e.png">

**Comment by tsiege** [comment]
:+1:  @Dharmoslap, did you figure out what caused this?
